# Generated by Django 5.1.7 on 2025-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
