# Generated by Django 5.1.7 on 2025-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyze', '0002_resume_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
