# Generated by Django 4.2.7 on 2025-09-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyze', '0004_job_description_delete_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_description',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='job_description',
            name='name',
        ),
    ]
