# Generated by Django 4.2.7 on 2025-09-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyze', '0005_remove_job_description_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_description',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
